object frmPrincipal: TfrmPrincipal
  Left = 0
  Top = 0
  Caption = 'DelphiToHero'
  ClientHeight = 706
  ClientWidth = 1284
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 1284
    Height = 706
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    ExplicitTop = 8
    ExplicitWidth = 911
    ExplicitHeight = 665
    object pnlMenu: TPanel
      Left = 0
      Top = 0
      Width = 161
      Height = 706
      Align = alLeft
      BevelOuter = bvNone
      ParentBackground = False
      TabOrder = 0
      ExplicitLeft = -6
      ExplicitHeight = 665
      object btnPrincipal: TSpeedButton
        Left = 0
        Top = 57
        Width = 161
        Height = 56
        Align = alTop
        Caption = 'PRINCIPAL'
        Flat = True
        OnClick = btnPrincipalClick
        ExplicitLeft = -6
        ExplicitTop = 63
      end
      object btnUsuarios: TSpeedButton
        Left = 0
        Top = 113
        Width = 161
        Height = 56
        Align = alTop
        Caption = 'USU'#193'RIOS'
        Flat = True
        OnClick = btnUsuariosClick
        ExplicitLeft = -6
        ExplicitTop = 161
      end
      object pnlLogo: TPanel
        Left = 0
        Top = 0
        Width = 161
        Height = 57
        Align = alTop
        BevelOuter = bvNone
        ParentBackground = False
        TabOrder = 0
      end
    end
    object pnlFull: TPanel
      Left = 161
      Top = 0
      Width = 1123
      Height = 706
      Align = alClient
      BevelOuter = bvNone
      ParentBackground = False
      TabOrder = 1
      ExplicitLeft = 167
      ExplicitWidth = 750
      ExplicitHeight = 665
      object pnlToolbar: TPanel
        Left = 0
        Top = 0
        Width = 1123
        Height = 57
        Align = alTop
        BevelOuter = bvNone
        ParentBackground = False
        TabOrder = 0
        ExplicitWidth = 750
      end
      object pnlContainer: TPanel
        Left = 0
        Top = 57
        Width = 1123
        Height = 649
        Align = alClient
        BevelOuter = bvNone
        ParentBackground = False
        TabOrder = 1
        ExplicitLeft = 280
        ExplicitTop = 312
        ExplicitWidth = 185
        ExplicitHeight = 41
      end
    end
  end
end
